### ISSUE TITLE
update requirement documentation to match tech stack

### ISSUE THREAD

**Issue by MattsCurrie** [ctakasakaubc/Minecraft_A-Minecraft_AI_Capstone#67]

**Comment by MattsCurrie** [comment]
done. We could check with Jeff about the dbs

**Comment by ctakasakaubc** [comment]
Still not 100% sure if we want to show alternatives to Electron since we are commited to it.
